### PR TITLE
HELM-40: Rework documentation structure, add basic installation and walk through.

### PR DESCRIPTION
**Pull request by j-white**
JIRA: https://issues.opennms.org/browse/HELM-40

### CODE REVIEW

**Comment by mvrueden** [comment]
Looks good to me (-:

Some thoughts:
 * OpenNMS and Grafana are styled in italic, whereas Helm is not.
 * The file `index-helm.html` points to `latest/project-info/index.html` which no longer exists. 
 * The information on how to build the docs is within the docs itself. A small hint in the overview README.md without accessing the asciibinder documentation would be nice.

**Comment by j-white** [comment]
> OpenNMS and Grafana are styled in italic, whereas Helm is not.

I have no real preference here.

> The file index-helm.html points to latest/project-info/index.html which no longer exists.

Fixed.

> The information on how to build the docs is within the generated docs itself. A small hint in the overview README.adoc without the need to view the official asciibinder documentation would be nice.

We'll need to rework the README completely, since it's displayed as the plugin overview on https://grafana.com/plugins/opennms-datasource.

> Edit:
> Some more thoughts:
> 
> Do we have to add the (TM) thingy on the Meridian naming?

Added.

> Should we add some copyright information?

Added a new page with some basic legal info.

**Comment by mvrueden** [comment]
>> OpenNMS and Grafana are styled in italic, whereas Helm is not.
>
> I have no real preference here.

Me neither, as long as it is consistent (-:

**Comment by j-white** [comment]
> OpenNMS and Grafana are styled in italic, whereas Helm is not.
> I have no real preference here.
> Me neither, as long as it is consistent (-:

Fair point. I went ahead and removed the italics.

I now only use them when I want to draw attention to a particular word/acronym.

**Pull request merged**
